### ISSUE TITLE
Why isn't the build done with the correct tag already?

### ISSUE THREAD

**Issue by ipsq** [tutumcloud/builder#43]

**Comment by pchico83** [comment]
Hi @ipsq Could you elaborate on this a little bit? I don't understand the issue as it is created.

**Comment by ipsq** [comment]
When the Dockerfile is built, it is tagged as this: `docker build --rm --force-rm -t this .`

Only to be retagged later on into the final image name. Why don't we do `docker build --rm --force-rm -t $IMAGE_NAME .` in the first place?

**Comment by fermayo** [comment]
This was done so one could use `image: this` in the `docker-compose.test.yml` to avoid rebuilding the image. Unfortunately, this was broken in docker-compose 1.3.2, so now it does not make much sense. Hopefully they will fix it so we can leverage caching the image independently from `$IMAGE_NAME`.
