### ISSUE TITLE
Add a hook that takes over build, test and push

### ISSUE THREAD

**Issue by ipsq** [tutumcloud/builder#45]
There are some Scala, Java and also Ruby plugins that automate the compilation, testing and pushing of the whole project. 

[sbt-native-packager](http://www.scala-sbt.org/sbt-native-packager/formats/docker.html) is a good example of this. It compiles, tests and pushes the project with one command. I ultimately worked around this issue by providing an empty push and test script but I think there should be a nicer implementation to support the JVM and Ruby users among us.

**Comment by fermayo** [comment]
This has been implemented: https://github.com/tutumcloud/builder#hooks
