### ISSUE TITLE
Pull submodules by default; or option for --recursive

### ISSUE THREAD

**Issue by modius** [tutumcloud/builder#46]
Docker Hub pulls submodules by default so it surprised me that **builder** doesn't.  Would be great to have this option on by default, but if not then perhaps an ENV to apply `--recursive` to the git pull.

**Comment by modius** [comment]
To get this done in the interim I added a `./hooks/post_checkout` like so:

```
#!/bin/sh
git --version
echo "Init submodule "
git submodule init
echo "Update submodule "
git submodule update --force
echo "Submodule status "
git submodule status
```

**Comment by kop** [comment]
@fermayo, can this be merged into the master? My project deployment is stuck because of this issue... :)
