### ISSUE TITLE
On docker hub, we do not have any tag for specific versions

### ISSUE THREAD

**Issue by sunshineo** [tutumcloud/builder#67]
Can someone build on dockerhub based on the tags? Or are we waiting for v1?
<img width="403" alt="tutumcloud_builder_github" src="https://cloud.githubusercontent.com/assets/1072766/10469296/1d52b78a-71b9-11e5-82be-55ab523bebd8.png">
<img width="454" alt="tutumcloud_builder_dockerhub" src="https://cloud.githubusercontent.com/assets/1072766/10469295/1d4ff928-71b9-11e5-8e1d-6df5708c970d.png">

**Comment by fermayo** [comment]
done

**Comment by sunshineo** [comment]
Awesome! Waiting for a new tag!
