### ISSUE TITLE
Specify Dockerfile

### ISSUE THREAD

**Issue by cduzan** [tutumcloud/builder#69]
I know there's a way to specify the Dockerfile path, but is there a way to specify the actual Dockerfile name? Even if that includes just adding the file name at the end of the path.

This would be helpful for when you need different builds for different environments. Is there a tool or a flag I am missing that would allow this capability?

Thanks

**Comment by timsuchanek** [comment]
You could use the `hooks/build` hook, by adding a file with the name `build` to the folder `hooks` in your repo.
In that file just override the current command:
```sh
docker build --rm --force-rm -t this .
```
with
```sh
docker build --rm --force-rm -t -f "DOCKERFILE_NAME" this .
```

**Comment by cduzan** [comment]
Awesome! Thanks @timsuchanek   I briefly read about the hooks in some of the documentation but I didn't see too much on it. I'll definitely have to take a deeper look at that.
