### ISSUE TITLE
Wrong status at Github check

### ISSUE THREAD

**Issue by bezelga** [tutumcloud/builder#74]
I am not sure if this is a builder problem, but can be somehow related.

I am building my image with tutum private registry, the image is successfully built Tutum timeline:

```
Image built in 3 minutes and 30 seconds
Tests passed in 1 minutes and 44 seconds
Image pushed in 1 minutes and 42 seconds
Build process returned exit code 0
Build in 'tutum' succeeded in 0:07:25
```

But at Github status, it is always displayed as a fail:

![screen shot 2015-12-07 at 2 29 05 pm](https://cloud.githubusercontent.com/assets/22406/11643744/24925556-9d2d-11e5-935b-d0ad2f061a40.png)

**Comment by fermayo** [comment]
Thanks for reporting this - as the GitHub status is updated by the Tutum service and not this builder container, can you please send us an email to support@tutum.co with your account name so we can check why is this happening? Thanks!
