### ISSUE TITLE
Linked container networking fails inside builder but not outside

### ISSUE THREAD

**Issue by rolo** [tutumcloud/builder#75]
Hi there.

I'm having problems getting my automated tests to run via builder when the same docker-compose config works locally. My `sut` service can't access my linked postgres container. I've tinkered and boiled it down to a simple example to demonstrate what's happening in the attached archive. ([builder-example.zip](https://github.com/tutumcloud/builder/files/63878/builder-example.zip)
) It seems as though there might be some difference in how networking works when running in builder vs outside of it. 

The docker-compose.test.yml looks like this:

    postgres:
      image: postgres
    sut:
      build: .
      command: psql -h postgres -U postgres -c"SELECT"
      links:
        - postgres

If I run this locally with:

    docker-compose -f docker-compose.test.yml run sut

You'll see that it connects to the postgres server and runs a select.

If I run this using builder like this:

    docker run --volumes-from builder_cache --rm -it --privileged -v $HOME/.docker:/.docker:ro -v $(pwd):/app tutum/builder $IMAGE_NAME

I get an error about not being able to connect to the server:

    psql: could not connect to server: Connection refused
	Is the server running on host "postgres" (172.18.0.1) and accepting
	TCP/IP connections on port 5432?

I've changed this to use a test on a redis image, and it connected fine. I'm suspecting it might be something to do with where the postgres container allows connections from, so this could well be outside the scope of being a builder issue, however I'd suggest if that's the case it would be good to document what the difference is as I'd imagine this is a fairly common use case.

Incase it's of any help, these are the `/etc/hosts` files for the `sut` container both inside and outside of builder:

With builder:

    172.18.0.2	9c9736d3feb5
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters
    172.18.0.1	postgres_1 fdfbca5c1793 91afecc37e98_postgres_1
    172.18.0.1	91afecc37e98_postgres_1 fdfbca5c1793
    172.18.0.1	postgres fdfbca5c1793 91afecc37e98_postgres_1
    172.18.0.1	91afecc37e98_postgres_1
    172.18.0.1	91afecc37e98_postgres_1.bridge
    172.18.0.2	91afecc37e98_sut_1
    172.18.0.2	91afecc37e98_sut_1.bridge

With compose:

    172.17.0.7	b1d06bbcc331
    127.0.0.1	localhost
    ::1	localhost ip6-localhost ip6-loopback
    fe00::0	ip6-localnet
    ff00::0	ip6-mcastprefix
    ff02::1	ip6-allnodes
    ff02::2	ip6-allrouters
    172.17.0.6	builderexample_postgres_1 209e66edd8f9
    172.17.0.6	postgres 209e66edd8f9 builderexample_postgres_1
    172.17.0.6	postgres_1 209e66edd8f9 builderexample_postgres_1

Thanks loads for any help.

Rolo.

**Comment by rolo** [comment]
This is a race condition with container create time. I can make it work by changing the sut container command to wait 10 seconds before executing with this:

    command: bash -c "sleep 10 && <my command>"

I expect I can do something smarter than this to wait until the port is available or something, but this is working for now. Thanks to Fernando at Tutum for help with this.

**Comment by fermayo** [comment]
You're welcome @rolo :)
