### ISSUE TITLE
Upload artifacts from a pull request

### ISSUE THREAD

**Issue by sjackman** [tutumcloud/builder#83]
Hi. I'm using Docker Cloud automated builds. I have a `docker-compose.test.yml` that runs some tests and produces some build artifacts (files produced by the tests). I'd like to upload these build artifacts after `docker-compose.test.yml` to a service such as Bintray or Amazon S3. I'd like to be able to do this for both `master` branch build as well as the pull requests of contributors. Is there documentation on how to upload artifacts using `docker-compose.test.yml`?

**Comment by pchico83** [comment]
Hi @sjackman DC does not directly support build artifacts but you can use our hooks to this end.
You can make your test container to write to a host folder mounted as volume, and use the "post_test" to upload these artifacts wherever you want.
More information about hooks here: 
https://github.com/tutumcloud/builder#hooks

**Comment by sjackman** [comment]
Thanks. Any suggestion on how best to pass the auth credentials necessary for uploading the artifacts to the post_test hook when builds are also enabled for contributor's pull requests without exposing those credentials to the contributor? I'm thinking of something similar to how [`GIT_ID_RSA`](https://github.com/tutumcloud/builder/blob/staging/build.sh#L58) is used for cloning the code.

**Comment by pchico83** [comment]
@sjackman I cannot think any. I have created an issue to support build artifacts in DC. Thanks

**Comment by sjackman** [comment]
Can you point me to a link to the issue so that I can comment over there?

**Comment by pchico83** [comment]
@sjackman We are working on a public issue tracker, but it is not ready yet. TBH, I don't think build artifacts will get into the product before DockerCon, we already have very packed roadmaps. I will let you know when it gets to development.

**Comment by sjackman** [comment]
Fair enough. A public issues tracker would be quite helpful. For the record, I'd like a way of setting environment variables that contain the authorization keys for a particular hook, such as `hooks/post_test`, and make sure that they keys are not exposed (by not setting the environment variables) if the user has modified `hooks/post_test` in their pull request.
